# Generated by Django 4.0 on 2021-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_alter_usuario_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_mod',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_reg',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
