# Generated by Django 4.0 on 2021-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_alter_solicitud_fecha_mod_alter_solicitud_fecha_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Dirigido a'),
        ),
    ]
