# Generated by Django 3.2.9 on 2021-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_alter_solicitud_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('comprobado', 'Comprobado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=150, verbose_name='estatus'),
        ),
    ]
