# Generated by Django 3.2.9 on 2021-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_alter_solicitud_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=150, verbose_name='estatus'),
        ),
    ]
