# Generated by Django 3.2.9 on 2021-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0010_remove_solicitud_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='firmado',
            field=models.CharField(choices=[('autógrafo', 'Autógrafo'), ('sifen', 'Sifen')], max_length=150, verbose_name='firmado'),
        ),
    ]
