# Generated by Django 3.2.9 on 2021-12-29 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0012_alter_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
