# Generated by Django 3.2.9 on 2021-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_solicitud_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_reg',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
