# Generated by Django 3.2.9 on 2022-01-02 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0014_auto_20211231_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
