# Generated by Django 3.2.9 on 2022-01-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0015_alter_solicitud_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'default_permissions': [], 'permissions': [('create_requests', 'Crear solicitudes'), ('view_requests', 'Ver solicitudes'), ('edit_requests', 'Editar solicitudes'), ('delete_requests', 'Eliminar solicitudes'), ('list_requests', 'Listar solicitudes'), ('option', 'Opciones')]},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
