# Generated by Django 4.1 on 2022-09-19 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0017_alter_solicitud_options_reducciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducciones',
            name='tipo',
            field=models.CharField(choices=[('t1', 'Tipo 1'), ('t2', 'Tipo 2')], max_length=30, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='reducciones',
            name='ejecutivo',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reducciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
