# Generated by Django 4.1 on 2022-09-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0019_alter_reducciones_options_alter_reducciones_folio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reducciones',
            options={'default_permissions': [], 'ordering': ['-fecha_reg'], 'permissions': [('create_requests', 'Crear solicitudes'), ('view_requests', 'Ver solicitudes'), ('edit_requests', 'Editar solicitudes'), ('delete_requests', 'Eliminar solicitudes'), ('list_requests', 'Listar solicitudes'), ('option_red', 'Opciones')]},
        ),
        migrations.AddField(
            model_name='reducciones',
            name='no_oficio',
            field=models.CharField(choices=[('n1', '400-58-00-02-01-2022'), ('n2', '400-58-00-02-02-2022'), ('n3', '400-58-00-03-00-2022')], max_length=100, null=True, verbose_name='Selecciona el no. de oficio'),
        ),
        migrations.AddField(
            model_name='reducciones',
            name='txt_folio',
            field=models.CharField(max_length=100, null=True, verbose_name='Número de folio'),
        ),
        migrations.AlterField(
            model_name='reducciones',
            name='oficio',
            field=models.CharField(max_length=100, verbose_name='Determinante'),
        ),
        migrations.AlterField(
            model_name='reducciones',
            name='tipo',
            field=models.CharField(choices=[('t1', 'RED. ART. 74 CFF'), ('t2', 'RED. ART. 41Y74 CFF')], max_length=30, null=True, verbose_name='Tipo'),
        ),
    ]
