# Generated by Django 4.1 on 2022-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0021_indicadores_alter_reducciones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='porcentaje',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
