# Generated by Django 4.1 on 2022-11-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0022_indicadores_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
