# Generated by Django 4.1 on 2022-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0023_indicadores_cantidad_alter_indicadores_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='porcentaje',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
