# Generated by Django 4.1 on 2022-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0025_alter_indicadores_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
