# Generated by Django 4.1 on 2022-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0026_alter_indicadores_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='periodo',
            field=models.CharField(choices=[('p1', '1'), ('p2', '2'), ('p3', '3')], default='p1', editable=False, max_length=3),
        ),
    ]
